### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Simon-Davies** [boku7/SPAWN#1]
I am compiling on Kali Linux:

x86_64-w64-mingw32-gcc -c spawn.x64.c -o spawn.x64.o
spawn.x64.c: In function ‘SpawnProcess’:
spawn.x64.c:24:5: error: unknown type name ‘STARTUPINFOEX’; did you mean ‘STARTUPINFO’?
   24 |     STARTUPINFOEX sInfoEx = { sizeof(sInfoEx) };
      |     ^~~~~~~~~~~~~
      |     STARTUPINFO
spawn.x64.c:41:22: error: ‘PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON’ undeclared (first use in this function)
   41 |     DWORD64 policy = PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spawn.x64.c:41:22: note: each undeclared identifier is reported only once for each function it appears in
spawn.x64.c:64:59: error: ‘PROC_THREAD_ATTRIBUTE_PARENT_PROCESS’ undeclared (first use in this function); did you mean ‘PROC_THREAD_ATTRIBUTE_PROTECTION_LEVEL’?
   64 |     KERNEL32$UpdateProcThreadAttribute(pAttributeList, 0, PROC_THREAD_ATTRIBUTE_PARENT_PROCESS, &hProc, sizeof(HANDLE), NULL, NULL);
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           PROC_THREAD_ATTRIBUTE_PROTECTION_LEVEL
spawn.x64.c:66:59: error: ‘PROC_THREAD_ATTRIBUTE_MITIGATION_POLICY’ undeclared (first use in this function); did you mean ‘PROC_THREAD_ATTRIBUTE_PROTECTION_LEVEL’?
   66 |     KERNEL32$UpdateProcThreadAttribute(pAttributeList, 0, PROC_THREAD_ATTRIBUTE_MITIGATION_POLICY, &policy, sizeof(policy), NULL, NULL);
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           PROC_THREAD_ATTRIBUTE_PROTECTION_LEVEL
spawn.x64.c:67:12: error: request for member ‘lpAttributeList’ in something not a structure or union
   67 |     sInfoEx.lpAttributeList = pAttributeList;

**Comment by boku7** [comment]
Will look into it. I have only tested compiling from macos atm.

**Comment by boku7** [comment]
Great catch! Strange that it compiles fine on macOS but doesn't include the headers on linux. I've manually defined them and tested them using Kali. Seems to be fixed now. Let me know if you experience the same. Again, great catch and thank you for the heads up!

**Comment by Simon-Davies** [comment]
Thanks mate
